### ISSUE TITLE
Displaying decorated functions?

### ISSUE THREAD

**Issue by ejolly** [mkdocstrings/mkdocstrings#162]
Apologies if this has been answered elsewhere, but I couldn't seem to find it in #73 or #126. 

If I have a function that's using a decorator from another library how do I get it to show up in mkdocstrings? E.g.

```python
# lib/stuff.py

from toolz import memoize

@memoize
def my_decorated_func(args):
    """
    Does stuff

    Returns:
        [type]: [description]
    """


def test_func():
    """
    Does stuff

    Returns:
        [type]: [description]
    """
    pass

```

Now in a markdown file if I do:

```
# Stuff module

::: lib.stuff

```

Only `test_func` shows up, but `my_decorated_func` does not. I've played with the filters in the `markdown.yml` but that hasn't helped either.

`mkdoc` version: 1.1.2  
`mkdocs-material` version: 6.0.2  
`mkdocs-material-extensions` version: 1.0.1
`mkdocstrings` version: 0.13.6

**Comment by ejolly** [comment]
hey @pawamoy just wanted to check in on this in case you got a chance to check it out. No worries if not and sorry if I'm coming across pushy!

**Comment by pawamoy** [comment]
> and sorry if I'm coming across pushy!

You're not, don't worry :slightly_smiling_face: Being ping'd works for me!

So, it should definitely work, there's nothing special to do for decorated functions, so I'll mark this as unconfirmed until I try it myself and replicate!

**Comment by ejolly** [comment]
@pawamoy does it matter if functions have _multiple_ decorations? You can see [here](https://github.com/ejolly/utilz/blob/master/utilz/ops.py#L35) for example in a repo I'm working on how this function has 2 decorators. 

But in doesn't show up at all in the [documentation site](http://eshinjolly.com/utilz/api/ops/). This is true of the deployed docs I've linked to, and if I run locally with `mkdocs serve`

**Comment by pawamoy** [comment]
Every object is currently passed through `inspect.unwrap`, but there might be cases that slip through it, not sure :confused:

**Comment by datGnomeLife** [comment]
This also impacting us as well. We have build tasks using `invoke` and every function has `@task` decorating it. Love the project!

**Comment by devjit-doordash** [comment]
This is also impacting us - are there any updates? Loving the project - so convenient!

**Comment by pawamoy** [comment]
OK I ran some tests, and found the issue.

First, note that a decorator can return an object completely different from the original function. If that object does not set its `__name__`, `__doc__` and `__wrapped__` attributes properly, `pytkdocs` won't be able to handle it. For example, [`toolz.memoize` does it](https://github.com/pytoolz/toolz/blob/master/toolz/functoolz.py#L463) while [`invoke.task` doesn't](https://github.com/pyinvoke/invoke/blob/ed94c59f1eacc700dac3815530493e0809fe001d/invoke/tasks.py#L368).

Second, there's a bug in `pytkdocs`: instead of checking the *unwrapped* object's module, it's currently checking the *wrapped* object's module, which will be the module where the type/function that is returned by the decorator was defined. See https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/loader.py#L422 and line 424.

So the fix seems obvious, `inspect.getmodule(member)` -> `inspect.getmodule(child_node.obj)`, but it will need testing :slightly_smiling_face: 

And for `invoke` tasks, someone should send a PR to at least set `__doc__` and `__wrapped__` to the final object returned by the decorator.

**Comment by dberzano** [comment]
Hey, chiming in... the following does not generate any documentation for `myfunction()` when the decorator `deco()` is used - this is a reproducer not using any extra library.

```py
def deco(fun):
    def wrapped():
        print('begin')
        fun()
        print('end')
    return wrapped

@deco
def myfunction():
    """Do nothing."""
    pass
```

@pawamoy I have actually tried to patch [this](https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/loader.py#L422) and [this](https://github.com/mkdocstrings/pytkdocs/blob/master/src/pytkdocs/loader.py#L424) as suggested, in pytkdocs:

```diff
-                if child_node.is_class() and node.root.obj is inspect.getmodule(member):
+                if child_node.is_class() and node.root.obj is inspect.getmodule(child_node.obj):
                     root_object.add_child(self.get_class_documentation(child_node))
-                elif child_node.is_function() and node.root.obj is inspect.getmodule(member):
+                elif child_node.is_function() and node.root.obj is inspect.getmodule(child_node.obj):
```

but it does not help with the above example. Not sure whether my comment is useful here... if you happen to find a tentative solution I'll be happy to test it/help 🙂

**Comment by pawamoy** [comment]
I'd say this is not supported, try to do this: https://mkdocstrings.github.io/troubleshooting/#my-wrapped-function-shows-documentationcode-for-its-wrapper-instead-of-its-own

**Comment by dberzano** [comment]
I am amazed, it did the trick! Thanks so much!

**Comment by pawamoy** [comment]
Fixed in https://github.com/mkdocstrings/pytkdocs/pull/109

**Comment by higorc-mck** [comment]
I have a kinda weird and very specific case here: my decorator strips out the second element of the tuple returned by the function, and leaves only the first, like this:

```python
def decorator(
    func: Callable[_PS, tuple[_RT, Any]],
) -> Callable[_PS, _RT]:
    @wraps(func)
    def wrapper(*args: _PS.args, **kwargs: _PS.kwargs) -> _RT:
        ret_val, extra_val = func(*args, **kwargs)

        # do something with extra val

        return ret_val

    # Explicitly add the information that this wrapper
    # strips out the second return element from `func`
    wrapper.__annotations__["return"] = get_type_hints(func)["return"].__args__[0]
    return wrapper
```

Inspecting my annotations after a function has been decorated shows that it has been correctly patched:

```python
@decorator
def my_func(a: int) -> tuple[int, int]: 
    return (1, 2)

my_func  # <function __main__.my_func(a: 'int') -> int>
```

yet my documentation still shows the original `tuple[int, int]` return annotation. Do you know of a reason why this is not working? Would appreciate any feedback, and would definitely contribute if I could find where to xD

TIA!

**Comment by pawamoy** [comment]
Hi @higorc-mck, could you copy your question into a new [Q/A discussion](https://github.com/mkdocstrings/mkdocstrings/discussions/categories/q-a) please? :slightly_smiling_face:

**Comment by higorc-mck** [comment]
Absolutely, sorry about that.

**Comment by higorc-mck** [comment]
#663, would really appreciate any answer, even an "it's impossible with the current dependencies" (though that would hurt). Thank you for the amazing plugin @pawamoy!

**Comment by pawamoy** [comment]
I'll have some time today to craft one :)
