### ISSUE TITLE
Support documenting overloaded methods

### ISSUE THREAD

**Issue by shashankrnr32** [mkdocstrings/mkdocstrings#308]
**Is your feature request related to a problem? Please describe.**

Using `typing`'s overload decorator, its possible to _overload_ methods in python. mkdocstrings currently doesn't honor the documentation provided to the all overloaded methods in the file. 

**Describe the solution you'd like**

mkdocstrings should parse all the overloaded methods for the docstrings and document all of them, maybe with an `overloaded` tag. 

**Describe alternatives you've considered**

NA

**Additional context**

<details>
<summary>Here is a sample code I used to generate documentation</summary>

```python
from typing import overload, Tuple, Any


@overload
def process(response: None) -> None:
    """
    Return None from taking None
    Args:
        response: None

    Returns:
        None :)
    """
    ...


@overload
def process(response: int) -> Tuple[int, str]:
    """
    Return tuple from int
    Args:
        response: some integer

    Returns:

    """
    ...


@overload
def process(response: bytes) -> str:
    """
    Return String from bytes input
    Args:
        response: Bytes

    Returns:
        Some string
    """
    ...


def process(response) -> Any:
    """
    Generic description
    Args:
        response:

    Returns:
        Something
    """
    return response

```
</details>

The screenshot documentation produced by mkdocstrings right now

<img width="738" alt="Screenshot 2021-08-20 at 4 38 00 PM" src="https://user-images.githubusercontent.com/29425899/130224587-887bfa67-96a6-4646-9e8d-afe1869e0736.png">

Thank you!!

**Comment by pawamoy** [comment]
Hello @shashankrnr32, very sorry for the late reply :bow: 

This issue is a typical limitation of pytkdocs' design: it loads (imports) code, and then introspect the objects in memory. Since at runtime (more like import time) the `@overload`-decorated method are overwritten by the actual implementation, only one member for this method appear in the class object. There is no way around that.

But! Fortunately, I'm working on a new tool to replace pytkdocs. This new tool will only parse the code instead of executing it, so the `@overload` decorator will definitely be supported :smile:

**Comment by shashankrnr32** [comment]
Thank you for the reply @pawamoy with an explanation about the limitations of pytkdocs. Great to know that there is a new initiative to replace pytkdocs with a better version. 

Personally I wouldn't mind if you close the issue with an appropriate label.  

Hope to see the new project soon!! 😄

**Comment by pawamoy** [comment]
Version 0.17.0 of Griffe now supports `typing.overload` :slightly_smiling_face: 
This will allow us to improve the rendering of overloaded methods in the Python handler :smile: 
I'd appreciate if interested users could post some HTML mock-ups: how do you want it to look?

**Comment by multimeric** [comment]
I would be happy to see the overloads as just a list of function signatures stacked vertically.

**Comment by BlueGlassBlock** [comment]
Hi there, I've just looked at the experimental python handler and played with it.
After copying some templates, I got the following:

![image](https://user-images.githubusercontent.com/50769752/197535389-791df326-3c55-44a8-9110-80541bd16e9e.png)

Maybe this is a good starting point? Anyway, this definitely needs polishing, so I will continue to work on it.

**Comment by BlueGlassBlock** [comment]
Currently I have some problems with design of the overall look.

- How should overloads be presented? Where should they be placed?

	A1. I think it's best to let user decide whether to "nest" them (just like class and children) or put them in an admonition block (not that sure). (That leads to the position problem described below.)

    A2. Currently I like placing it under the function's name, before the implementation's signature.
    That leads to the second problem:

- How should `overload` look like when `separate_signature` is disabled?

    Without `separate_signature` enabled, the signature (parameter list) will be integrated into the heading. That might be quite confusing (and probably ugly, since quite lots of `overload` implementations involves something like `*args` and `**kwargs`. Should we fall back to the `separate_signature` behavior, or the implementation signature is kept?

- How to configure the presentation of implementation?

    Maybe provide a separate configurable value and let users decide whether to show complete implementation signature, or only showing the implementation source (if `show_source` is on)? In that case, how should we deal with the docstring of the implementation?

I'm eager to hear from @pawamoy, as he's the project owner 🙂

**Comment by BlueGlassBlock** [comment]
I've already published my progress here: https://github.com/BlueGlassBlock/mkdocstrings-handler-python/tree/overload

**Comment by pawamoy** [comment]
Hey @BlueGlassBlock, thanks for your help, that's very nice! I did follow your progress, and will eventually form a proper answer, but for now I'm short on time and trying to finish other things :sweat_smile: Just wanted you to know :slightly_smiling_face:

**Comment by tlambert03** [comment]
Just came to request this feature.  Great to see that it's well underway!

I had taken some screenshots of my sphinx apidocs  to show, and perhaps they're still of use.
Here's how my function looks in sphinx, and I kinda like it:

<img width="719" alt="Screen Shot 2022-11-18 at 7 17 12 PM" src="https://user-images.githubusercontent.com/1609449/202823813-4fcabbd4-43ba-49cf-93d4-ab0b448130b9.png">

I recognize that that's not `table` mode... and will of course be a need for that to document each signature, but if it's possible to support  annotated signatures one directly after the other, it's a nice concise way to look at it

**Comment by pawamoy** [comment]
No, the templates for overloaded functions are still not implemented.

**Comment by pawamoy** [comment]
Version 1.6.2.1.5.0 of mkdocstrings-python Insiders now supports rendering function signature overloads automatically. It simply renders each signature stacked up vertically. It uses only the docstring of the implementation. If you would like to discuss improvements, please open a new issue!
